name: Publish NPM (canary)
on:
    workflow_dispatch:
    pull_request: #TODO: clean up
        branches:
            - main
jobs:
    publish-npm-package:
        runs-on: ubuntu-latest
        outputs:
            pkg_version: ${{ steps.bump-version.outputs.pkg_version }}
            full_pkg_version: ${{ steps.publish-package.outputs.full_pkg_version }}
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: "https://registry.npmjs.org"
                  # Defaults to the user or organization that owns the workflow file
                  scope: "@perp"

              # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
            - name: Get Yarn cache directory
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Use Yarn cache
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: yarn install --prefer-offline --frozen-lockfile

            - name: Config Git
              run: |
                  git config --global user.email "dev@perp.fi"
                  git config --global user.name "Perpetual Protocol"

            - name: Bump version
              id: bump-version
              # update package.json version, add CHANGELOG & commit changes
              run: |
                  yarn bump-version
                  echo "::set-output name=pkg_version::$(node -p "require('./package.json').version")"
                  echo "::set-output name=release_env::canary"

            - name: Build package
              run: TRACK=canary yarn build
              env:
                  APP_STAGE: ${{ steps.bump-version.outputs.release_env }}

            - name: Publish package
              id: publish-package
              run: |
                  echo "::set-output name=full_pkg_version::${{ steps.bump-version.outputs.pkg_version }}-${{ steps.bump-version.outputs.release_env }}"
                  echo ${{ steps.bump-version.outputs.release_env }}
                  echo ${{ steps.publish-package.outputs.full_pkg_version }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Git push version change
              run:
                  echo "Git push"
                  # yarn release --tag ${{ steps.bump-version.outputs.release_env }} --new-version "${{ steps.publish-package.outputs.full_pkg_version }}"

    discord-notification-npm-package:
        name: Discord Notification for publishing npm package
        if: ${{ always() }}
        needs: [publish-npm-package]
        runs-on: ubuntu-latest
        steps:
            - name: issue success notification
              if: needs.publish-npm-package.result == 'success'
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "**[@perp/sdk-curie: dev1]** @perp/sdk-curie version: **${{ needs.publish-npm-package.outputs.full_pkg_version }}**  published successfully ✅"

            - name: issue failure notification
              if: needs.publish-npm-package.result != 'success'
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "**[@perp/sdk-curie: dev1]** @perp/sdk-curie version: **${{ needs.publish-npm-package.outputs.pkg_version }}** failed to publish 🛑"
