name: Publish NPM (canary)
on:
    push:
        branches:
            - 'release/*'
jobs:
    publish-npm-package:
        runs-on: ubuntu-latest
        outputs:
            pkg_version: ${{ steps.bump-version.outputs.pkg_version }}
            full_pkg_version: ${{ steps.bump-version.outputs.full_pkg_version }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: '0' # For bump-version to have all the commit history

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: "https://registry.npmjs.org"
                  # Defaults to the user or organization that owns the workflow file
                  scope: "@perp"

              # See: https://github.com/actions/cache/blob/main/examples.md#node---yarn
            - name: Get Yarn cache directory
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Use Yarn cache
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: yarn install --prefer-offline --frozen-lockfile

            - name: Config Git
              run: |
                  git config --global user.email "dev@perp.fi"
                  git config --global user.name "Perpetual Protocol"

            # update package.json version, add CHANGELOG & commit changes
            - name: Bump version
              id: bump-version
              run: |
                  yarn bump-version
                  RELEASE_ENV=canary
                  PKG_VERSION=$(node -p "require('./package.json').version")
                  FULL_PKG_VERSION="${PKG_VERSION}-${RELEASE_ENV}"
                  echo "::set-output name=pkg_version::$PKG_VERSION"
                  echo "::set-output name=release_env::$RELEASE_ENV"
                  echo "::set-output name=full_pkg_version::$FULL_PKG_VERSION"

            - name: Build package
              run: TRACK=${{ steps.bump-version.outputs.release_env }} yarn build

            - name: Publish package
              id: publish-package
              run: |
                  echo tag: ${{ steps.bump-version.outputs.release_env }}
                  echo version: ${{ steps.bump-version.outputs.full_pkg_version }}
                  yarn release --tag ${{ steps.bump-version.outputs.release_env }} --new-version "${{ steps.bump-version.outputs.full_pkg_version }}"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Git push version change
              run: git push

    discord-notification-npm-package:
        name: Discord Notification for publishing npm package
        if: ${{ always() }}
        needs: [publish-npm-package]
        runs-on: ubuntu-latest
        steps:
            - name: issue success notification
              if: needs.publish-npm-package.result == 'success'
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "**[@perp/sdk-curie: dev1]** @perp/sdk-curie version: **${{ needs.publish-npm-package.outputs.full_pkg_version }}**  published successfully ✅"

            - name: issue failure notification
              if: needs.publish-npm-package.result != 'success'
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                  args: "**[@perp/sdk-curie: dev1]** @perp/sdk-curie version: **${{ needs.publish-npm-package.outputs.full_pkg_version }}** failed to publish 🛑"
